import React, { useState, useEffect } from 'react';
import { FileText, Download, Eye, Calendar } from 'lucide-react';

interface ReportData {
  hasReport: boolean;
  filename?: string;
  s3Url?: string;
}

export default function UserReports() {
  const [reportData, setReportData] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchUserReport();
  }, []);

  const fetchUserReport = async () => {
    try {
      setLoading(true);
      const token = localStorage.getItem('auth_token') || sessionStorage.getItem('auth_token') || '';
      
      const response = await fetch('/api/user-report', {
        headers: {
          'token': token,
        },
      });
      const data = await response.json();
      
      if (data.success) {
        setReportData(data.data);
      }
    } catch (error) {
      console.error('Error fetching user report:', error);
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = async () => {
    if (reportData?.s3Url) {
      try {
        // Fetch the PDF file
        const response = await fetch(reportData.s3Url);
        const blob = await response.blob();
        
        // Create a download link
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        
        // Extract filename from URL or use a default name
        const filename = reportData.filename || 'my-report.pdf';
        link.download = filename;
        
        // Trigger download
        document.body.appendChild(link);
        link.click();
        
        // Cleanup
        document.body.removeChild(link);
        window.URL.revokeObjectURL(url);
      } catch (error) {
        console.error('Error downloading report:', error);
        alert('Failed to download report');
      }
    }
  };

  const handleView = () => {
    if (reportData?.s3Url) {
      window.open(reportData.s3Url, '_blank');
    }
  };

  if (loading) {
    return (
      <div className="bg-white rounded-lg border border-gray-200 p-6">
        <div className="flex items-center justify-center py-8">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-themeTeal"></div>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-lg border border-gray-200 p-6">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-lg font-semibold text-themeTeal flex items-center">
          <FileText className="h-5 w-5 mr-2" />
          Your Reports
        </h3>
      </div>

      {reportData?.hasReport ? (
        <div className="space-y-4">
          <div className="flex items-center space-x-3 p-4 bg-gray-50 rounded-lg">
            <FileText className="h-8 w-8 text-themeTeal" />
            <div className="flex-1">
              <h4 className="font-medium text-gray-900">{reportData.filename}</h4>
            </div>
          </div>
          
          <div className="flex space-x-3">
            <button
              onClick={handleView}
              className="flex items-center space-x-2 px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors"
            >
              <Eye className="h-4 w-4" />
              <span>View Report</span>
            </button>
            
            <button
              onClick={handleDownload}
              className="flex items-center space-x-2 px-4 py-2 bg-green-500 text-white rounded-lg hover:bg-green-600 transition-colors"
            >
              <Download className="h-4 w-4" />
              <span>Download</span>
            </button>
          </div>
        </div>
      ) : (
        <div className="text-center py-8">
          <FileText className="h-12 w-12 text-gray-400 mx-auto mb-4" />
          <h4 className="text-lg font-medium text-gray-900 mb-2">No Reports Available</h4>
          <p className="text-gray-500">
            Your personalized reports will appear here once they are generated by our team.
          </p>
        </div>
      )}
    </div>
  );
}
