export {default as PriceChartSection} from "./priceChartSection";
export {default as ScorecardSection} from "./scorecardSection";
export {default as InvestmentRationaleSection} from "./investmentRationaleSection";
export {default as PerformanceBenchmarkSection} from "./performanceBenchmarkSection";
export {default as SectorOutlookSection} from "./sectorOutlookSection";
export {default as FinancialPerformanceSection} from "./financialPerformanceSection";
export {default as ShareholdingSection} from "./shareholdingSection";
export {default as NewsSection} from "./newsSection";
export {default as FaqSection} from "./faqSection";